__Linear SVC (Support Vector Classifier) Example__

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Target']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head(5)

sepal-length  sepal-width  petal-length  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
dataset.Target.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [5]:
X = dataset.loc[:, 'sepal-length':'petal-width' ]
y = dataset.iloc[:, 4]

In [6]:
X.columns

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width'], dtype='object')

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
from sklearn.svm import LinearSVC

In [10]:
# Create support vector classifier
svc = LinearSVC(C=0.10)

model = svc.fit(X_train, y_train)

In [11]:
test_predictions=svc.predict(X_test)
train_predictions=svc.predict(X_train)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[9 1 0]
 [0 5 3]
 [0 3 9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.90      0.95        10
Iris-versicolor       0.56      0.62      0.59         8
 Iris-virginica       0.75      0.75      0.75        12

       accuracy                           0.77        30
      macro avg       0.77      0.76      0.76        30
   weighted avg       0.78      0.77      0.77        30

Train Accuracy: 92.5
Test Accuracy: 76.66666666666667


In [13]:
from sklearn.svm import SVC

__Create a SVC classifier using a linear kernel__

In [14]:
linear_svm = SVC(kernel='linear', C=1,gamma=0.01, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[10  0  0]
 [ 0  8  0]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         8
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Train Accuracy: 96.66666666666667
Test Accuracy: 100.0


__Create a SVC classifier using a RBF kernel__

In [15]:
linear_svm = SVC(kernel='rbf', C=1,gamma=0.01, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[10  0  0]
 [ 0  6  2]
 [ 0  5  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.55      0.75      0.63         8
 Iris-virginica       0.78      0.58      0.67        12

       accuracy                           0.77        30
      macro avg       0.77      0.78      0.77        30
   weighted avg       0.79      0.77      0.77        30

Train Accuracy: 90.0
Test Accuracy: 76.66666666666667


__Create a SVC classifier using a Polynomial kernel__

In [17]:
linear_svm = SVC(kernel='poly', C=10,gamma=0.2, random_state=0)
# Train the classifier
linear_svm.fit(X_train, y_train)

test_predictions=linear_svm.predict(X_test)
train_predictions=linear_svm.predict(X_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[10  0  0]
 [ 0  8  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.89      1.00      0.94         8
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

Train Accuracy: 97.5
Test Accuracy: 96.66666666666667


In [ ]:
#SVM BLOG Link

In [ ]:
#https://chrisalbon.com/machine_learning/support_vector_machines/svc_parameters_using_rbf_kernel/
#https://www.youtube.com/watch?v=3liCbRZPrZA